# Generated by Django 6.0.3 on 2026-04-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_room_usermodel_is_active_usermodel_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
