# Generated by Django 6.0.3 on 2026-04-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_discipline_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='classsession',
            unique_together={('room', 'date', 'start_time')},
        ),
    ]
