class AttendanceRepository:
    
    def get_by_id(self, attendance_id):...
    
    def save(self, attendance):...
    
    def update(self, attendance):...
    
    def delete(self, attendance_id):...
    
    def get_all(self):...
    
    def _to_entity(self, model):...
    
    def _to_class_session_entity(self, model):...
    
    def _to_user_entity(self, model):...