class ClassSessionRepository:
    
    def get_by_id(self, class_session_id):...
    
    def save(self, class_session):...
    
    def update(self, class_session):...
    
    def delete(self, class_session_id):...
    
    def get_all(self):...
    
    def _to_entity(self, model):...

    def _to_discipline_entity(self, model):...
    
    def _to_room_entity(self, model):...
    
    def _to_user_entity(self, model):...