class DisciplineRepository:
    
    def get_by_id(self, discipline_id):...
    
    def save(self, discipline):...
    
    def update(self, discipline):...
    
    def delete(self, discipline_id):...
    
    def get_all(self):...
    
    def exists_by_code(self, code):...
    
    def _to_entity(self, model):...
    
    def _to_user_entity(self, model):...