class ProfessorRepository:
    
    def get_by_id(self, professor_id):...
    
    def save(self, professor):...
    
    def update(self, professor):...
    
    def delete(self, professor_id):...
    
    def get_all(self):...
    
    def _to_entity(self, model):...