class RoomRepository:
    
    def get_by_id(self, student_id):...
    
    def save(self, student):...
    
    def update(self, student):...
    
    def delete(self, student_id):...
    
    def get_all(self):...
    
    def _to_entity(self, model):...